from datetime import datetime

class AdvisoryService:
    def __init__(self):
        # Thresholds configured per NCC Quality of Service Regulation 2012 / 2025 Guidelines
        self.thresholds = {
            "DropCallRate": 1.0,           # Max 1%
            "CallSetupSuccessRate": 98.0,  # Min 98%
            "InternetLatency": 100         # Max 100ms (Example)
        }

    def process_qos_event(self, metric: str, value: float) -> dict:
        """
        Evaluates a QoS metric. If breach, generates a remediation report context.
        """
        threshold = self.thresholds.get(metric)
        if threshold is None:
            return {"status": "ignored", "reason": "Unknown metric"}

        breach = False
        if metric == "CallSetupSuccessRate":
            if value < threshold:
                breach = True
        else:
            # Default logic: Lower is better
            if value > threshold:
                breach = True

        if not breach:
            return {"status": "ok", "metric": metric, "value": value}

        # Breach Detected -> Generate Report
        report_context = self._generate_remediation_report(metric, value, threshold)
        # In real system, this context goes to the PDF renderer and then Email
        return {"status": "breach_alerted", "report": report_context}

    def _generate_remediation_report(self, metric, value, threshold):
        return {
            "title": f"URGENT: QoS Breach - {metric}",
            "generated_at": datetime.utcnow().isoformat(),
            "breach_details": {
                "metric": metric,
                "current_value": value,
                "regulatory_threshold": threshold,
                "status": "CRITICAL"
            },
            "custody_chain": "Auto-generated by Board Advisory Module",
            "action_required": "Immediate remediation plan required from CTO to Board."
        }
