from datetime import datetime
from src.modules.configuration.service import ConfigurationService

class AdvisoryService:
    def __init__(self, config_service: ConfigurationService = None):
        self.config_service = config_service or ConfigurationService()

    def process_qos_event(self, metric: str, value: float) -> dict:
        """
        Evaluates a QoS metric against dynamic NCC rules.
        """
        rule = self.config_service.get_rule_for_metric("NCC", metric)
        if not rule:
            return {"status": "ignored", "reason": "No regulatory rule found for metric"}

        breach = False
        
        # Check Breach Condition
        if rule.operator == "GT":
            if value > rule.threshold:
                breach = True
        elif rule.operator == "LT":
            if value < rule.threshold:
                breach = True
        
        if not breach:
            return {"status": "ok", "metric": metric, "value": value}

        # Breach Detected -> Generate Report
        return {"status": "breach_alerted", "report": self._generate_remediation_report(metric, value, rule.threshold)}

    def _generate_remediation_report(self, metric, value, threshold):
        return {
            "title": f"URGENT: QoS Breach - {metric}",
            "generated_at": datetime.utcnow().isoformat(),
            "breach_details": {
                "metric": metric,
                "current_value": value,
                "regulatory_threshold": threshold,
                "status": "CRITICAL"
            },
            "custody_chain": "Auto-generated by Board Advisory Module",
            "action_required": "Immediate remediation plan required from CTO to Board."
        }
